name: Scheduled Update

# Run every 10 mins during Bungie's working hours. 
# The Action takes ~10 seconds to run if there is no new manifest.
# Github give 2000 minutes (120_000 seconds) per month
on:
  schedule: 
    - cron: "*/10 15-23 * * *"
    - cron: "*/10 0-2 * * *"
  push:
    branches:
      - main

jobs:
  update_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run Node.js Script
        run: node apps/definition_minifier/runner/index.js

      - name: Check Exit Status
        id: check-status
        run: echo "Success"

      - name: Commit and Push Changes
        if: steps.check-status.outcome == 'success'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Commit new definitions"
          git push

      - name: Send Slack Notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"@nigel New Destiny Item Definitions were just created"}' $SLACK_WEBHOOK_URL
