name: Scheduled Update

on:
  schedule:
    - cron: "*/10 15-23 * * *"
    - cron: "*/10 0-2 * * *"
  push:
    branches:
      - main

jobs:
  update_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run Node.js Script
        run: node apps/definition_minifier/runner/index.js

      - name: Check Exit Status
        id: check-status
        run: echo "Success"

      - name: Commit and Push Changes
        if: steps.check-status.outcome == 'success'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Commit new definitions
          git push
